fix: Comment out jupyter-for-emacs to skip build error
this breaks because of some python version issue. No headspace to fix it now because I need to get shit done but the gist is basically:

```
ERROR: Coud not find a version that satisfies the requirement importlib-resources; python_version < "3.9" (from keyring) (from versions: none)
ERROR: No matching distribution found for importlib-resources; python_version < "3.9"
```

python3.8-keyring-23.13.1.drv was the culprit here which seemed rellated to the emacs jupyter thing.